name: openai every day backup
run-name:  openai every day backup
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  download-openai-api-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .github/workflows/download.sh
      - name: Commit files
        run: |
          git config --global user.email "xshalk@163.com"
          git config --global user.name "shalk"
          git add .
          git commit --message "update openai api yaml"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

